### ISSUE TITLE
🚀 [Feature] Battlebot auto join queue.

### ISSUE THREAD

**Issue by den13501** [betayi/core-by#1]
## 🚀 Feature

Hi betayi, I found your repo, the custom change is very useful, I have a idea, to make battle bots to auto join queue when they talk to battlegroud NPC or enter bg portal, thus they dont need to input command, thanks!

**Comment by betayi** [comment]
nice suggestion, i will try , while i get some time ~

**Comment by betayi** [comment]
talk to battlemaster can summon a battlebot to queue .now
